name: 'OtterDoc'
description: 'Let AI write your documentation for you'
author: 'OtterDoc'
inputs:
  key:
    required: true
    description: 'An API key for OtterDoc'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'terminal'
  color: 'purple'