name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  key:
    required: true
    description: 'An API key for OtterDoc'
runs:
  using: 'node16'
  main: 'dist/index.js'
